name: "NanoPulse Gateway"
description: "NanoPulse Gateway service"
version: "0.1.0-test.1"
slug: "nanopulse_gateway"
init: false
services:
  - "mqtt:need"
arch:
  - aarch64
  - amd64
devices:
  - /dev/ttyACM0
options:
  name: "np-gateway"
  radio: "rak2287_8xx_usb"
schema:
  name: "str"
  radio: "list(rak2287_8xx_usb)"
